name: flutter_asset_gen_example
description: Example for flutter_asset_gen
publish_to: "none"
environment:
  sdk: ">=3.2.0 <4.0.0"

# Depend on the package by relative path (pub ignores example’s dev deps).
dependencies:
  flutter:
    sdk: flutter
  flutter_asset_gen:
    path: ../

dev_dependencies:
  build_runner: ^2.4.0
